### ISSUE TITLE
Fix running tests in multi-project builds

### ISSUE THREAD

**Issue by JonaLoeffler** [rcasia/neotest-java#100]
With the latest plugin version, running tests in my multi-project gradle build fails. 

The project consists of a number gradle sub-projects like `com.company.app.web.server.<component>` for about 10 components. Each of these then has `src/test/java`.

```
cat: build/neotest-java/classpath.txt: No such file or directory
error: --class-path requires an argument
Usage: javac <options> <source files>
use --help for a list of possible options
```

The statusline briefly shows `src/test/java is not accessible by the current user!`, then `Error reading file: /tmp/neotest-java/<some kind of id>/TEST-junit-jupiter.xml`

This is my Lazy config for neotest:

```lua
return {
  {
    'rcasia/neotest-java',
    ft = 'java',
    dependencies = {
      'nvim-neotest/neotest',
      dependencies = {
        'nvim-neotest/nvim-nio',
        'nvim-lua/plenary.nvim',
        'antoinemadec/FixCursorHold.nvim',
        'nvim-treesitter/nvim-treesitter',
      },
    },
    config = function()
      require('neotest').setup {
        adapters = {
          require 'neotest-java' {
            ignore_wrapper = false, -- whether to ignore maven/gradle wrapper
          },
        },
      }

      vim.keymap.set('n', '<leader>tp', function()
        require('neotest').run.run(vim.uv.cwd())
      end, { desc = '[T]est [P]project', noremap = true })

      vim.keymap.set('n', '<leader>tf', function()
        require('neotest').run.run(vim.fn.expand '%')
      end, { desc = '[T]est [F]ile', noremap = true })

      vim.keymap.set('n', '<leader>tr', function()
        require('neotest').run.run()
      end, { desc = '[T]est [R]un', noremap = true })

      vim.keymap.set('n', '<leader>ts', function()
        require('neotest').run.stop()
      end, { desc = '[T]est [S]top', noremap = true })

      vim.keymap.set('n', '<leader>ta', function()
        require('neotest').run.attach()
      end, { desc = '[T]est [A]ttach', noremap = true })

      vim.keymap.set('n', '<leader>to', function()
        require('neotest').output.open()
      end, { desc = '[T]est output [O]pen', noremap = true })
    end,
  },
}
```

`build/neotest-java/classpath.txt` does exist in the working directory, but is empty.

Version `v.1.10.0` still works as before.

**Comment by steffsommer** [comment]
This might be the biggest blocker for people to use this plugin in real world settings

**Comment by steffsommer** [comment]
I created a related issue with potential solutions, which was moved to discussions. I am linking it here for reference: https://github.com/rcasia/neotest-java/discussions/149

**Comment by rcasia** [comment]
Sorry for the latency, I had no much time for it. I just merged the feature https://github.com/rcasia/neotest-java/commit/9e6e8cf630d32d620700c4fbcf489e18292600ec.

I'll close this issue but feel completely free to reopen! :call_me_hand:

**Comment by rcasia** [comment]
Hi @LorenzoBettini, do you have any examples?

**Comment by LorenzoBettini** [comment]
@rcasia this a minimal example https://github.com/LorenzoBettini/maven-multimodule-example

**Comment by rcasia** [comment]
> this a minimal example https://github.com/LorenzoBettini/maven-multimodule-example

This project is using Junit4, which currently is not supported.

**Comment by LorenzoBettini** [comment]
Not supported in a multi project? Because in a single project it works: it detects all the tests in a single project using junit4.

**Comment by rcasia** [comment]
> Not supported in a multi project? Because in a single project it works: it detects all the tests in a single project using junit4.

Sorry, you are right.

Junit4 is supported, but not junit4 with the format of the old junit3 which is being implemented here: https://github.com/LorenzoBettini/maven-multimodule-example/blob/master/my-app-parent/my-app-module1/src/test/java/org/my/app/module1/AppTest.

The main incompatibility between neotest-java and junit3 format is that the test methods don't have the Test annotation class, so they will not be detected to be run.
