### ISSUE TITLE
Use the mvn or gradle wrapper by default

### ISSUE THREAD

**Issue by rcasia** [rcasia/neotest-java#27]
As the title says... Use the mvn or gradle wrapper by default.

Also allow users to not use the wrapper changing the configuration.

**Comment by nsapse** [comment]
Would love this (or alternatively just documentation provided on how to use the wrapper rather than a global binary)

**Comment by rcasia** [comment]
Thanks! I'll be implementing this soon, and I'll keep you posted. Currently, there's no workaround available.

**Comment by rcasia** [comment]
@nsapse merged. If you find any wrong feel free to reopen. Thanks!

**Comment by nsapse** [comment]
Thanks for this work, @rcasia. Will test it out a bit tomorrow at work.
