### ISSUE TITLE
Cannot execute nested test class

### ISSUE THREAD

**Issue by eruizc-dev** [rcasia/neotest-java#54]
When tying to execute the test below it fails stating that`app.SomeTest.app.SomeNestedTest.*` doesn't exist. That's because it should try and run `app.SomeTest$SomeNestedTest.*` instead.

```java
package app;

public class SomeTest {
    public static class SomeNestedTest {
        @Test
        public void someTest() {
            assertEquals(1 + 1, 2);
        } 
    }
}
```

**Comment by rcasia** [comment]
I am already checking this out. Thank you for the report!

**Comment by eruizc-dev** [comment]
Awesome! Let me know if you need help, I'm willing to contribute

**Comment by rcasia** [comment]
Having classes as namespaces should bring the posibility to construct the right command. I'll assing you this issue. If you need any guidance, don't hesitate to ask.

**Comment by eruizc-dev** [comment]
I'm having trouble running my tests locally and it's making it difficult to see how my changes affect the project. How do you run them?

I've tried with [neotest-plenary](https://github.com/nvim-neotest/neotest-plenary) and with the barebons ` nvim --headless -c "PlenaryBustedDirectory ."` but 2 test while loading `neotest-java` and the others hang.
I've also inspected your CI and found that while it succeeds there are a couple hidden failures in there: https://github.com/rcasia/neotest-java/actions/runs/6805839060/job/18506092499#step:5:42

**Comment by eruizc-dev** [comment]
Oh forget about the CI thing, I went back and noticed that those were java tests and not lua's :sweat_smile: , but I still have trouble executing the other. I do wonder if it has something to do with the way I have [configured Lazy.nvim](https://github.com/eruizc-dev/eruizc-dev/blob/master/dotfiles/xdg_config_home/nvim/lua/eruizc-dev/plugins/testing.lua#L2-L45).

**Comment by rcasia** [comment]
I needed to set the absolute path to `minimal_init.vim` for the neotest-plenary config. Something like this:
```lua
{
    'nvim-neotest/neotest-plenary',
    min_init = ".../neotest-java/tests/minimal_init.vim"
}
```
Also I just created [CONTRIBUTING](https://github.com/rcasia/neotest-java/blob/main/CONTRIBUTING.md), might be useful.

**Comment by rcasia** [comment]
I've just pushed a bugfix related to the newly introduced namespaces. This fix could be a starting point for addressing the issue with nested classes.

**Comment by rcasia** [comment]
Close this issue is currently fixed.
