### ISSUE TITLE
Add DAP support

### ISSUE THREAD

**Issue by rcasia** [rcasia/neotest-java#59]
I'm relatively new to using DAP, so I'll need to delve into its functionalities and documentation to better understand the 'what' and 'how-to's. This is important for https://github.com/LazyVim/LazyVim/issues/1984.

**Comment by appelgriebsch** [comment]
hey, I guess if you have `nvim-jdtls` and `nvim-dap` wired up properly you can trigger something like this to debug the test method at the current position: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/java.lua#L209.

btw: thanks for this nice add-on to neotest <3

**Comment by appelgriebsch** [comment]
OK, looks like latest `java-test` is no longer available as vsix from GitHub repo and the old version doesn't play nice with recent jdtls versions :angry: 

see https://github.com/mfussenegger/nvim-jdtls/issues/565

**Comment by rcasia** [comment]
Yes, by the time I wanted to try it I couldn't and found lots of references to this problem. I believe there is still a way. I'll keep an eye on it.

**Comment by appelgriebsch** [comment]
@rcasia have you seen the new GH org `nvim-java` (https://github.com/nvim-java) already? I started working on an extension based on it in my Nv project (incl. your `neotest-java` adapter): https://github.com/appelgriebsch/Nv/blob/main/lua/plugins/extras/lang/java.lua

**Comment by rcasia** [comment]
FYI @appelgriebsch, DAP integration into neotest-java is complete after my time away.
