### ISSUE TITLE
"No such file or directory"  trying to run tests

### ISSUE THREAD

**Issue by Cirius1792** [rcasia/neotest-java#69]
Hi, I'm experiencing the following error when I try to run the test in my project: 
```
neotest-java: ...iu/AppData/Local/nvim-data/lazy/neotest/lua/nio/init.lua:105: The coroutine failed with this message:
...m-data/lazy/plenary.nvim/lua/plenary/context_manager.lua:47: C:\Users\ciriu\Documents\Projects\expense-app-v3\expenses-domain/target/surefire-reports/TEST-src\test\com\clt\usecase\PayUseCaseTest.xml: No such file or directory
stack traceback:
        [C]: in function 'assert'
        ...m-data/lazy/plenary.nvim/lua/plenary/context_manager.lua:47: in function 'open'
        ...zy/neotest-java/lua/neotest-java/core/result_builder.lua:142: in function 'results'
        ...cal/nvim-data/lazy/neotest/lua/neotest/client/runner.lua:132: in function '_run_spec'
        ...cal/nvim-data/lazy/neotest/lua/neotest/client/runner.lua:89: in function <...cal/nvim-data/lazy/neotest/lua/neotest/client/runner.lua:88>
```
Am I missing something in how should I configure or use this plugin? 

If it can help, the project on which I am trying to use this neotest-java is [this](https://github.com/Cirius1792/expense-app-v3) 
and [this](https://github.com/Cirius1792/nvim-config) is my neovim configuration

EDIT: The problem seems to occur only on Windows, while it works fine on linux. Can it be related to the os file path separator?

**Comment by rcasia** [comment]
Hi, @Cirius1792 . 

> EDIT: The problem seems to occur only on Windows, while it works fine on linux. Can it be related to the os file path separator?

That's exactly the reason.
Sorry for that! I had that on mind but never took the time.

Feel free to open a PR! (else I could work on it next week if no one has done it).

**Comment by Jakub-Ignatowicz** [comment]
Exactly same issue appears on MacOS as well.

**Comment by bkrusz** [comment]
> Exactly same issue appears on MacOS as well.

To add to this, it appears to be using java class notation (/surefire-reports/TEST-com.example.TestClass.xml) instead of path notation (/surefire-reports/TEST-com/example/TestClass.xml)

**Comment by apgrc** [comment]
This happens on linux as well: 

```
neotest-java: ~/.local/share/nvim/lazy/neotest/lua/nio/init.lua:105: The coroutine failed with this message: 
...e/nvim/lazy/plenary.nvim/lua/plenary/context_manager.lua:47: ~/Documents/projects/java/guava/guava-tests/target/surefire-reports/TEST-test.com.google.common.base.Utf8Test.xml: No such file or directory
stack traceback:
	[C]: in function 'assert'
	...e/nvim/lazy/plenary.nvim/lua/plenary/context_manager.lua:47: in function 'open'
	...zy/neotest-java/lua/neotest-java/core/result_builder.lua:142: in function 'results'
	...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:132: in function '_run_spec'
	...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:89: in function <...al/share/nvim/lazy/neotest/lua/neotest/client/runner.lua:88>
```
I'm trying to run [Utf8Test.java#L79](https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/base/Utf8Test.java#L79)

**Comment by rcasia** [comment]
Hey there! I've merged the fix. Can you check if it works on your systems and let me know if there are still any issues? Thanks!
