### ISSUE TITLE
Tests are marked as "skipped" when using @DisplayName

### ISSUE THREAD

**Issue by M4urici0GM** [rcasia/neotest-java#70]
## Description

Apparently it has an issue that tests with `@DisplayName` are marked as skipped, no matter if passed or not:

![image](https://github.com/rcasia/neotest-java/assets/37017091/ec18b8bf-2975-4d2d-a892-87912b37f7d4)

when i run the test:
![image](https://github.com/rcasia/neotest-java/assets/37017091/4e5d3666-ae0f-4c3c-a889-fe11c4cb00a1)

I was able to fix this issue on my fork, the thing is i think i've broke the paramiterized tests xD
Idk if is something you can reuse, i refactored a bunch of stuff

![image](https://github.com/rcasia/neotest-java/assets/37017091/472aae08-2754-429c-af67-c15e1c3e4988)

**Comment by rcasia** [comment]
Thank you. Hopefully I will be able to check it out soon.

**Comment by rcasia** [comment]
Fixed in #80
